# Generated by Django 4.2.3 on 2023-07-31 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_vericationcode_info'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VericationCode_info',
            new_name='VerificationCode_info',
        ),
        migrations.AlterModelTable(
            name='verificationcode_info',
            table='VerificationCode_info',
        ),
    ]
