# Generated by Django 4.2.3 on 2023-08-05 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_rename_vericationcode_info_verificationcode_info_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLoginInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_time', models.DateTimeField(auto_now_add=True)),
                ('device_info', models.CharField(max_length=100)),
                ('ip_address', models.GenericIPAddressField()),
                ('login_status', models.CharField(max_length=10)),
                ('login_type', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
            options={
                'db_table': 'UserLoginInfo',
                'ordering': ['-login_time'],
            },
        ),
    ]
