# Generated by Django 4.2.3 on 2023-08-08 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_userlogininfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=1000, verbose_name='user_id')),
                ('num', models.IntegerField(verbose_name='num')),
            ],
            options={
                'db_table': 'Login_info',
            },
        ),
    ]
